### ISSUE TITLE
Permission denied (os error 13) when writing to file from Dockerfile

### ISSUE THREAD

**Issue by luPhz** [denoland/deno_docker#317]
I setup a directory like in the example https://github.com/denoland/deno_docker/tree/main/example

the only content of main.ts is 
```await Deno.writeTextFile("hello.txt", "Hello World");```
like in the deno examples.

running this on ubuntu
```$ sudo docker build -t app . && docker run -it -v ${PWD}:/app -p 1993:1993 app```
lead to the error message
```error: Uncaught (in promise) PermissionDenied: Permission denied (os error 13): writefile 'hello.txt'
await Deno.writeTextFile("hello.txt", "Hello World");
^
    at async writeFile (ext:deno_fs/30_fs.js:805:7)
    at async file:///app/main.ts:1:1```

Removing `USER deno` from the dockerfile works for the moment. What is going on here?

**Comment by irbull** [comment]
Not much to add other than I experienced this too. It's working fine in our production (linux) systems, but on my development machine (mac M1) this is failing to write (new) files. Writing to existing files seems to work ok.

**Comment by irbull** [comment]
In my case, the Dockerfile was copying in a directory with the same name as the directory I was trying to create / write to in Deno. The copy operation resulted in different permissions, and it failed to write. Of course, if I didn't user `USER deno`, then Docker defaults to `USER root` and this worked. Maybe not related to your problem.
