### ISSUE TITLE
deno_docker example fails with 'TypeError: Deno.writeAll is not a function'

### ISSUE THREAD

**Issue by und-miller** [denoland/deno_docker#424]
Copying the code verbatim from the docker example does not work.

Can be reproduced by:
1. Copy the code from https://github.com/denoland/deno_docker/tree/main/example
2. Run `docker build -t app .`
3. Run `docker run -it --init -p 1993:1993 app`
4. From another terminal run ` curl http://localhost:1993`
5. Fails with the error below

```
error: Uncaught (in promise) TypeError: Deno.writeAll is not a function
      await Deno.writeAll(
                 ^
    at BufWriter.flush (https://deno.land/std@0.77.0/io/bufio.ts:468:18)
    at writeResponse (https://deno.land/std@0.77.0/http/_io.ts:288:16)
    at eventLoopTick (ext:core/01_core.js:175:7)
    at async ServerRequest.respond (https://deno.land/std@0.77.0/http/server.ts:84:7)
```

**Comment by dionjwa** [comment]
Also this fails the same way:

```sh
deno run -A --unstable https://deno.land/x/puppeteer@16.2.0/install.ts
```

**Comment by introvert** [comment]
any updates on this? we have the same issue

**Comment by kimdcottrell** [comment]
I ran into this. You can get past this by simply using this in the main.ts:

```
Deno.serve(
    { port: 1993, hostname: "0.0.0.0" }, 
    (_req) => new Response("Hello, world")
);
```

Seems to be related to a depreciation in 1.40 that was fully removed in 2.0.

https://deno.com/blog/v1.40#deprecations-stabilizations-and-removals
https://docs.deno.com/runtime/reference/migration_guide/

**Comment by Ahmad136140** [comment]
> Copying the code verbatim from the docker example does not work.
> 
> Can be reproduced by:
> 
> 1. Copy the code from https://github.com/denoland/deno_docker/tree/main/example
> 2. Run `docker build -t app .`
> 3. Run `docker run -it --init -p 1993:1993 app`
> 4. From another terminal run ` curl http://localhost:1993`
> 5. Fails with the error below
> 
> ```
> error: Uncaught (in promise) TypeError: Deno.writeAll is not a function
>       await Deno.writeAll(
>                  ^
>     at BufWriter.flush (https://deno.land/std@0.77.0/io/bufio.ts:468:18)
>     at writeResponse (https://deno.land/std@0.77.0/http/_io.ts:288:16)
>     at eventLoopTick (ext:core/01_core.js:175:7)
>     at async ServerRequest.respond (https://deno.land/std@0.77.0/http/server.ts:84:7)
> ```
