### ISSUE TITLE
Weird error when downloading modules

### ISSUE THREAD

**Issue by Kayxue** [denoland/deno_docker#439]
I have a project which can run with no error locally, but after I built the project to docker image, created container with the image and run it with docker on my computer, it run out with following error:
```
Downloading https://github.com/felix-schindler/deno-argon2/releases/download/v2.0.2/libdeno_argon2.so
2024-12-12 16:25:58 error: Uncaught (in promise) Error: Could not open library: Could not open library: /deno-dir/plug/https/github.com/901e77fb36a064d7e5d8cfea1f471efd18d8302970caec522cb2c388e33fbf4b.so: cannot open shared object file: No such file or directory
2024-12-12 16:25:58   return Deno.dlopen<S>(await download(options), symbols as any);
2024-12-12 16:25:58               ^
2024-12-12 16:25:58     at new DynamicLibrary (ext:deno_ffi/00_ffi.js:456:42)
2024-12-12 16:25:58     at Object.dlopen (ext:deno_ffi/00_ffi.js:562:10)
2024-12-12 16:25:58     at dlopen (https://jsr.io/@denosaurs/plug/1.0.6/mod.ts:158:15)
2024-12-12 16:25:58     at eventLoopTick (ext:core/01_core.js:175:7)
2024-12-12 16:25:58     at async https://jsr.io/@felix/argon2/2.0.2/lib/internal.ts:61:13
```
Already tried using image `denoland/deno:alpine` and `denoland/deno:latest` to build, but when the container start up, all end up with error above.

**Comment by M4RC3L05** [comment]
Maybe it is downloading the wrong `.so` file?

I to have deps that required downloading extra `.so` files bu in my case i decided to have them on the docker build step as 
```dockerfile
# ...
RUN deno eval "import '@db/sqlite'"
RUN deno eval "import '@b-fuze/deno-dom/native'"
#...
```

This way, there is no need to download the `.so` file each time the container runs as it will be cached as a docker image layer.
Hope it helps.
